# Generated by Django 3.2.6 on 2021-09-17 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_room', to=settings.AUTH_USER_MODEL, verbose_name='friend')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_room', to=settings.AUTH_USER_MODEL, verbose_name='starter')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_messages', to=settings.AUTH_USER_MODEL, verbose_name='friend')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='communications.room', verbose_name='room')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_messages', to=settings.AUTH_USER_MODEL, verbose_name='starter')),
            ],
        ),
    ]
