# Generated by Django 3.2.6 on 2021-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, editable=False, upload_to='images', verbose_name='photo'),
        ),
    ]
