# Generated by Django 3.2.6 on 2021-09-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210916_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='comment',
            new_name='post',
        ),
    ]
