# Generated by Django 3.2.6 on 2021-09-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210917_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
